### ISSUE TITLE
oh also can you make a vid for how to do this

### ISSUE THREAD

**Issue by justnothi** [CartoonChess/among-us-mac#10]
like can you do a vid?

**Comment by CartoonChess** [comment]
Instructions beyond those provided in the readme are currently outside the scope of the project. However, a user by the name of ReAnTech has made a Spanish-language [tutorial on YouTube](https://www.youtube.com/watch?v=22jm_QLAGTE). Hope that helps!

**Comment by justnothi** [comment]
thanks
