### ISSUE TITLE
"the action run applescript encountered an error not authorized to send apple events to system events."

### ISSUE THREAD

**Issue by justnothi** [CartoonChess/among-us-mac#11]
its says the action run applescript encountered an error not authorized to send apple events to system events. when i open the among us installer

**Comment by justnothi** [comment]
fixed but how?

**Comment by CartoonChess** [comment]
This sounds like a Gatekeeper or related macOS security issue. Giving the installer permissions in System Preferences, moving the app to /Applications, running as an administrator, or simply relaunching the app—these are the likely workarounds, I think. Thank you for the report!
