### ISSUE TITLE
"Among Us.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by CobreDev** [CartoonChess/among-us-mac#7]
I just downloaded the latest version of Among Us from itch.io, and the latest installers of everything. When I try to "patch" the Among Us app, it always tells me that it's damaged and can't open

**Comment by CobreDev** [comment]
Update: If I run the installer as sudo through terminal, it *seems* to work. Strange...

**Comment by CartoonChess** [comment]
Hi @CobreDev. Just to be sure, could you please provide your OS version and browser vendor, as well as whether your system user account has administrator privileges? Thanks.

**Comment by CobreDev** [comment]
I'm on Mojave 10.14, and using Safari. My account is the only account in the computer, so I have admin access

It's probably related to that other issue

**Comment by CartoonChess** [comment]
The installation relies on three items (installer, wrapper zip, and game files), but only the installer is signed and notarized. When you receive the error message, does it specify which app has the problem?

**Comment by CobreDev** [comment]
@CartoonChess No it didn't specify at all

Also sorry, I wish the GitHub iOS app had notifications
