### ISSUE TITLE
M1 (Apple silicon) compatibility

### ISSUE THREAD

**Issue by CartoonChess** [CartoonChess/among-us-mac#8]
The wine wrapper needs to be tested on non-Intel Macs, and solutions to any problems investigated.

**Comment by andresavic** [comment]
![CleanShot 2020-12-01 at 15 57 37@2x](https://user-images.githubusercontent.com/2312881/100756918-0855b600-33ee-11eb-949f-b503fd8943ac.png)
Works well 🎉

**Comment by CartoonChess** [comment]
Wow!.. I can’t say I was expecting this! Haha. Thank you for your quick response and good news, @andresavic!

**Comment by CartoonChess** [comment]
I just saw your [AmongKey](https://github.com/andresavic/AmongKey) repository. Am I correct in assuming then that your report comes from running the iOS version on M1?

**Comment by andresavic** [comment]
> I just saw your [AmongKey](https://github.com/andresavic/AmongKey) repository. Ah I correct in assuming then that your report comes from running the iOS version on M1?

Of course not. I used your Wine wrapper with the Steam windows version of Among Us 😊

**Comment by CartoonChess** [comment]
This is really surprising (but of course good) news! Thank you again. I wonder if your repository is a sufficient solution to #2

**Comment by andresavic** [comment]
Probably not. The "bad" parts of both worlds 😅
