### ISSUE TITLE
"free"

### ISSUE THREAD

**Issue by justnothi** [CartoonChess/among-us-mac#9]
Is this free cause it says it cost money! Can you please somehow make a free? Thank you!

**Comment by justnothi** [comment]
please make it free

**Comment by CartoonChess** [comment]
Hello @justnothi! Thank you for your interest in the project. This project has no official connection with the game, and is simply a tool to help run the game on macOS. While this tool is free, the game is not, and is entirely developed by [Innersloth](https://innersloth.com). If you're looking for a free solution, take a look at the iOS or Android versions. :)

**Comment by justnothi** [comment]
thanks
